# This is the example config from https://github.com/buildbot/buildbot-docker-example-config
# with the "db.env" file included directly here so the compose file can be pasted into Rancher
# and a stack spun up easily.
version: '2'
services:
  buildbot:
    image: buildbot/buildbot-master:master
    environment:
      # database parameters are shared between containers
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_USER=buildbot
      - POSTGRES_DB=buildbot
      # in master.cfg, this variable is str.format()ed with the environment variables
      - BUILDBOT_DB_URL=postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db/{POSTGRES_DB}
      # Other
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_CONFIG_URL=https://github.com/buildbot/buildbot-docker-example-config/archive/master.tar.gz
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"
  db:
    environment:
      # database parameters are shared between containers
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_USER=buildbot
      - POSTGRES_DB=buildbot
      # in master.cfg, this variable is str.format()ed with the environment variables
      - BUILDBOT_DB_URL=postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db/{POSTGRES_DB}
    image: "postgres:9.4"
    expose:
      - 5432

  worker:
    image: "buildbot/buildbot-worker:master"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: example-worker
      WORKERPASS: pass
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
      - buildbot
